language: ruby
rvm:
  - 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: $API_SECRET
  run:
    - 'rake db:migrate'
  app: $HEROKU_APP_NAME
  on:
    repo: Divoolej/workshops-netguru
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate